[project]
name = "text-to-speech-tts"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "edge-tts>=7.2.7",
    "gtts>=2.5.4",
    "pyttsx3>=2.99",
]
